{{- if .Values.frontend.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: {{ .Values.namespace }}
  labels:
    app: frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: {{ .Values.imageRegistry }}/crewup-frontend:{{ .Values.frontend.imageTag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.frontend.port }}
        env:
        - name: VITE_API_URL
          value: "https://{{ .Values.domain }}/api/v1"
        - name: VITE_KEYCLOAK_URL
          value: "{{ .Values.keycloak.url }}"
        - name: VITE_KEYCLOAK_REALM
          value: "{{ .Values.keycloak.realm }}"
        - name: VITE_KEYCLOAK_CLIENT_ID
          value: "{{ .Values.keycloak.clientId }}"
        - name: REACT_APP_EVENT_API
          value: "http://event:8000"
        - name: REACT_APP_GROUP_API
          value: "http://group:8000"
        - name: REACT_APP_RATING_API
          value: "http://rating:8000"
        - name: REACT_APP_SAFETY_API
          value: "http://safety:8000"
        - name: REACT_APP_USER_API
          value: "http://user:8000"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Values.namespace }}
  labels:
    app: frontend
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.frontend.port }}
    targetPort: {{ .Values.frontend.port }}
    protocol: TCP
  selector:
    app: frontend
{{- end }}
