{{- if .Values.rabbitmq.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: {{ .Values.namespace }}
  labels:
    app: rabbitmq
  annotations:
    # Prevent ArgoCD from recreating this if it exists
    argocd.argoproj.io/sync-options: Prune=false
type: Opaque
stringData:
  username: {{ .Values.rabbitmq.user | quote }}
  password: {{ .Values.rabbitmq.password | quote }}
  # Connection URL for services to use (cross-namespace access)
  url: "amqp://{{ .Values.rabbitmq.user }}:{{ .Values.rabbitmq.password }}@{{ .Values.rabbitmq.host }}.{{ .Values.rabbitmq.namespace }}:{{ .Values.rabbitmq.port }}/"
{{- end }}
