apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service-api
  labels:
    app: rabbitmq
spec:
  selector:
    app: rabbitmq
  type: ClusterIP  # Internal only - no external access
  ports:
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: prometheus
      protocol: TCP
      port: 15692
      targetPort: 15692
