apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  labels:
    app: rabbitmq
type: Opaque
stringData:
  username: {{ .Values.RabbitMQUser | quote }}
  password: {{ .Values.RabbitMQPassword | quote }}
  # Connection URL for services to use
  url: "amqp://{{ .Values.RabbitMQUser }}:{{ .Values.RabbitMQPassword }}@rabbitmq-service-api:5672/"
